apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ballast.fullname" . }}
  labels:
    {{- include "ballast.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods/resize"]
  verbs: ["patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["ballast.tightlinesoftware.com"]
  resources:
    - ballastconfigs
    - clusterresourcepolicies
    - metricssources
    - resourcepolicies
  verbs: ["get", "list", "watch"]
- apiGroups: ["ballast.tightlinesoftware.com"]
  resources: ["workloadprofiles"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["ballast.tightlinesoftware.com"]
  resources: ["workloadprofiles/status"]
  verbs: ["get", "update", "patch"]
