{{- if .Values.defaultMetricsSources.kubernetesMetrics.enabled }}
apiVersion: ballast.tightlinesoftware.com/v1
kind: MetricsSource
metadata:
  name: {{ .Values.defaultMetricsSources.kubernetesMetrics.name | quote }}
  labels:
    {{- include "ballast.labels" . | nindent 4 }}
spec:
  type: kubernetesMetrics
  config:
    pollInterval: {{ .Values.defaultMetricsSources.kubernetesMetrics.pollInterval | quote }}
    reservoirSize: {{ .Values.defaultMetricsSources.kubernetesMetrics.reservoirSize }}
{{- end }}
