{{- if .Values.leaderElect }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ballast.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ballast.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ballast.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "ballast.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
