# This rule is not used by the project ballast itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ballast.tightlinesoftware.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ballast
    app.kubernetes.io/managed-by: kustomize
  name: metricssource-admin-role
rules:
- apiGroups:
  - ballast.tightlinesoftware.com
  resources:
  - metricssources
  verbs:
  - '*'
- apiGroups:
  - ballast.tightlinesoftware.com
  resources:
  - metricssources/status
  verbs:
  - get
